#!/usr/bin/env python
# coding: utf-8
"""
Jolt : the Vim Package Management System

See http://vimjolts.appspot.com/
This is a script of vimjolts that can manage vimscript. below is our design
philosophy.
  * Automatic dependency resolution
  * Uninstallable
  * Searchable
"""

import os
import sys
import traceback

# sys.path[0] always refers to script's dirname.
sys.path = [os.path.join(sys.path[0], 'lib')] + sys.path
from jolt.commands import invoke_command
from jolt.config   import load_config


___name___ = "jolt"
___author___ = "The VimJolts Team"
#___license___ = ""
___version___ = "0.1"

if __name__ == '__main__':
  if len(sys.argv) == 1:
    invoke_command('help')
  try:
    load_config()
    invoke_command(sys.argv[1], sys.argv[2:])
  except TypeError:
    if not sys.exc_info()[2].tb_next:
      invoke_command('help');
  except KeyboardInterrupt:
    pass
  except SystemExit, e:
    sys.exit(e)
  except:
    traceback.print_exc()
    sys.exit(1)

# vim:set et ts=2 sw=2:
